#! /bin/sh

set -e

if [ -n "$INITRD" ] && [ "$INITRD" = 'No' ]; then
    exit 0
fi

# passing the kernel version is required
[ -z "$1" ] && exit 1



if [  -n "$2" ]; then
    # Where is the image located? We'll place the initrd there.
    boot=$(dirname "$2")
    bootarg="-b $boot"
fi

if [ -n "$DEB_MAINT_PARAMS" ]; then
    eval set -- "$DEB_MAINT_PARAMS"
    if [ -z "$1" ] || [ "$1" != "configure" ]; then
        exit 0;
    fi
fi



# 
update-initramfs -c -t -k "$1" $bootarg

