#! /usr/bin/perl
#                              -*- Mode: Perl -*- 
# debian.postinst --- 
# Author           : Manoj Srivastava ( srivasta@pilgrim.umass.edu ) 
# Created On       : Sat Apr 27 05:55:26 1996
# Created On Node  : melkor.pilgrim.umass.edu
# Last Modified By : root
# Last Modified On : Thu Jun 13 08:55:22 1996
# Last Machine Used: melkor.pilgrim.umass.edu
# Update Count     : 30
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
# 

$|=1;
# Predefined values:
my $ret;
my $confcmd = "/usr/sbin/kernel-packageconfig";

# Ignore all invocations uxcept when called on to configure.
exit 0 unless $ARGV[0] =~ /configure/;

# most of our work is done in /etc
chdir("/etc") or die "could not chdir to /etc:$!\n";

-x "$confcmd" || 
  die "Garbled installation: Could not find $confcmd";
$ret = system "$confcmd";
if ($ret) {
  my $ans;
  print "There was an error running $confcmd, and the package maybe \n";
  print "misconfigured.  Please run $confcmd by hand, or edit the file \n";
  print "/etc/kernel-pkg.conf by hand.\n";
  exit (1);
}
exit (0);
__END__
